version: "3.9"

services:

  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/public:/var/www/frontend/public:ro
      - ./auth-service/public:/var/www/auth-service/public:ro
      - ./ip-manager-service/public:/var/www/ip-manager-service/public:ro
      - ./gateway-service/public:/var/www/gateway-service/public:ro
    depends_on:
      - gateway-service
      - auth-service
      - ip-manager-service
    networks:
      - microservices

  gateway-service:
    build: ./gateway-service
    volumes:
      - ./gateway-service:/var/www/html
      - /var/www/html/vendor   
    networks:
      - microservices
    depends_on:
      - mysql
      - redis

  auth-service:
    build: ./auth-service
    volumes:
      - ./auth-service:/var/www/html
      - /var/www/html/vendor   
    networks:
      - microservices
    depends_on:
      - mysql
      - redis

  ip-manager-service:
    build: ./ip-manager-service
    volumes:
      - ./ip-manager-service:/var/www/html
      - /var/www/html/vendor
    networks:
      - microservices
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - microservices

  redis:
    image: redis:7-alpine
    networks:
      - microservices

volumes:
  mysql_data:

networks:
  microservices:
    driver: bridge